#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Elmah
{
    using System;
    using System.Collections.Generic;
    
    #line 2 "..\..\ErrorDetailPage.cshtml"
    using System.Globalization;
    
    #line default
    #line hidden
    
    #line 3 "..\..\ErrorDetailPage.cshtml"
    using System.IO;
    
    #line default
    #line hidden
    using System.Linq;
    using System.Text;
    
    #line 4 "..\..\ErrorDetailPage.cshtml"
    using System.Web;
    
    #line default
    #line hidden
    
    #line 5 "..\..\ErrorDetailPage.cshtml"
    using Elmah;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    internal partial class ErrorDetailPage : WebTemplateBase
    {
#line hidden

        public override void Execute()
        {


WriteLiteral("\r\n");







            
            #line 7 "..\..\ErrorDetailPage.cshtml"
  
    var basePageName = Request.ServerVariables["URL"];
    
    //
    // Retrieve the ID of the error to display and read it from 
    // the store.
    //

    var errorId = Request.QueryString["id"] ?? string.Empty;

    if (errorId.Length == 0)
    { 
        return;
    }

    var log = this.ErrorLog ?? ErrorLog.GetDefault(Context);
    var errorEntry = log.GetError(errorId);

    //
    // Perhaps the error has been deleted from the store? Whatever
    // the reason, bail out silently.
    //

    if (errorEntry == null)
    {
        Response.Status = HttpStatus.NotFound.ToString();

            
            #line default
            #line hidden
WriteLiteral("        <p>Error not found in log.</p>\r\n");


            
            #line 34 "..\..\ErrorDetailPage.cshtml"
        return;
    }

    var title = string.Format("Error: {0} [{1}]", errorEntry.Error.Type, errorEntry.Id);

    Layout = new Elmah.MasterPage
    {
        Context  = Context, /* TODO Consider not requiring this */
        Title    = title,
        Footnote = string.Format("This log is provided by the {0}.", log.Name),
        SpeedBarItems = new[] 
        {
            SpeedBar.Home.Format(basePageName),
            SpeedBar.Help,
            SpeedBar.About.Format(basePageName),
        },
    };

    var error = errorEntry.Error;


            
            #line default
            #line hidden
WriteLiteral("\r\n");



WriteLiteral("\r\n\r\n<h1 id=\"PageTitle\">");


            
            #line 59 "..\..\ErrorDetailPage.cshtml"
              Write(error.Message);

            
            #line default
            #line hidden
WriteLiteral("</h1>\r\n\r\n<p id=\"ErrorTitle\">");



WriteLiteral("<span id=\"ErrorType\">");


            
            #line 62 "..\..\ErrorDetailPage.cshtml"
                      Write(error.Type);

            
            #line default
            #line hidden
WriteLiteral("</span>");



WriteLiteral("<span id=\"ErrorTypeMessageSeparator\">: </span>");



WriteLiteral("<span id=\"ErrorMessage\">");


            
            #line 64 "..\..\ErrorDetailPage.cshtml"
                         Write(error.Message);

            
            #line default
            #line hidden
WriteLiteral("</span></p>\r\n\r\n");



WriteLiteral("\r\n\r\n");


            
            #line 74 "..\..\ErrorDetailPage.cshtml"
 if (error.Detail.Length != 0)
{

            
            #line default
            #line hidden
WriteLiteral("    <pre id=\"ErrorDetail\">");


            
            #line 76 "..\..\ErrorDetailPage.cshtml"
                     Write(MarkupStackTrace(error.Detail));

            
            #line default
            #line hidden
WriteLiteral("</pre>\r\n");


            
            #line 77 "..\..\ErrorDetailPage.cshtml"
}


            
            #line default
            #line hidden

            
            #line 83 "..\..\ErrorDetailPage.cshtml"
  

            
            #line default
            #line hidden
WriteLiteral("\r\n<p id=\"ErrorLogTime\">");


            
            #line 85 "..\..\ErrorDetailPage.cshtml"
                Write(string.Format(
    @"Logged on {0} at {1}",
    error.Time.ToLongDateString(),
    error.Time.ToLongTimeString()));

            
            #line default
            #line hidden
WriteLiteral("</p>\r\n\r\n");



WriteLiteral("\r\n\r\n<p>See also:</p>\r\n\r\n<ul>\r\n\r\n");



WriteLiteral("\r\n\r\n");


            
            #line 105 "..\..\ErrorDetailPage.cshtml"
     if (error.WebHostHtmlMessage.Length != 0)
    {
        var htmlUrl = basePageName + "/html?id=" + Uri.EscapeDataString(errorEntry.Id);

            
            #line default
            #line hidden
WriteLiteral("        <li><a href=\"");


            
            #line 108 "..\..\ErrorDetailPage.cshtml"
                Write(basePageName);

            
            #line default
            #line hidden
WriteLiteral("/html?id=");


            
            #line 108 "..\..\ErrorDetailPage.cshtml"
                                      Write(Uri.EscapeDataString(errorEntry.Id));

            
            #line default
            #line hidden
WriteLiteral("\">Original ASP.NET error page</a></li>\r\n");


            
            #line 109 "..\..\ErrorDetailPage.cshtml"
    }


            
            #line default
            #line hidden

            
            #line 113 "..\..\ErrorDetailPage.cshtml"
  

            
            #line default
            #line hidden
WriteLiteral("\r\n    <li>Raw/Source data in \r\n        <a rel=\"");


            
            #line 116 "..\..\ErrorDetailPage.cshtml"
           Write(HtmlLinkType.Alternate);

            
            #line default
            #line hidden
WriteLiteral("\" \r\n           type=\"application/xml\" \r\n           href=\"xml");


            
            #line 118 "..\..\ErrorDetailPage.cshtml"
                Write(Request.Url.Query);

            
            #line default
            #line hidden
WriteLiteral("\">XML</a>\r\n        or in\r\n        <a rel=\"");


            
            #line 120 "..\..\ErrorDetailPage.cshtml"
           Write(HtmlLinkType.Alternate);

            
            #line default
            #line hidden
WriteLiteral("\" \r\n           type=\"application/json\" \r\n           href=\"json");


            
            #line 122 "..\..\ErrorDetailPage.cshtml"
                 Write(Request.Url.Query);

            
            #line default
            #line hidden
WriteLiteral("\">JSON</a>\r\n    </li>\r\n</ul>\r\n\r\n");


            
            #line 126 "..\..\ErrorDetailPage.cshtml"
 if (error.UserComments.Length != 0)
{

            
            #line default
            #line hidden
WriteLiteral("    <div id=\"UserComments\">\r\n        <h2>User Comments</h2>\r\n    </div>\r\n");



WriteLiteral("    <pre>");


            
            #line 131 "..\..\ErrorDetailPage.cshtml"
    Write(error.UserComments);

            
            #line default
            #line hidden
WriteLiteral("</pre>\r\n");


            
            #line 132 "..\..\ErrorDetailPage.cshtml"
}

            
            #line default
            #line hidden
WriteLiteral("\r\n");


            
            #line 134 "..\..\ErrorDetailPage.cshtml"
  
    
            
            #line default
            #line hidden
            
            #line 135 "..\..\ErrorDetailPage.cshtml"
Write(MarkupCollection(error.ServerVariables, "ServerVariables", "Server Variables"));

            
            #line default
            #line hidden
            
            #line 135 "..\..\ErrorDetailPage.cshtml"
                                                                                   
    
            
            #line default
            #line hidden
            
            #line 136 "..\..\ErrorDetailPage.cshtml"
Write(MarkupCollection(error.SessionVariables, "SessionVariables", "Session Variables"));

            
            #line default
            #line hidden
            
            #line 136 "..\..\ErrorDetailPage.cshtml"
                                                                                      
    
            
            #line default
            #line hidden
            
            #line 137 "..\..\ErrorDetailPage.cshtml"
Write(MarkupCollection(error.QueryString, "QueryString", "Query String"));

            
            #line default
            #line hidden
            
            #line 137 "..\..\ErrorDetailPage.cshtml"
                                                                       
    
            
            #line default
            #line hidden
            
            #line 138 "..\..\ErrorDetailPage.cshtml"
Write(MarkupCollection(error.Cookies, "Cookies", "Cookies"));

            
            #line default
            #line hidden
            
            #line 138 "..\..\ErrorDetailPage.cshtml"
                                                          


            
            #line default
            #line hidden
WriteLiteral("\r\n");



WriteLiteral("\r\n");


        }
    }
}
#pragma warning restore 1591
